### ISSUE TITLE
Webapps not opening in SteamOS

### ISSUE THREAD

**Issue by pogipants** [ProfessorKaos64/SteamOS-Tools#105] opened 2015-12-08 19:40 UTC
Hi,

When installing the Netflix web app, when I launch it in SteamOS it opens and closes abruptly. When opening the script in Desktop mode, it launches in a small kiosk windows, like 500x400, and gives me this error in the terminal:

```
desktop@steamos:/usr/bin$ ./Netflix-Launch.sh 
No protocol specified
xdpyinfo:  unable to open display ":0".
xprop: error: Invalid window id format: -f.
Profile location /home/steam/antimicro/ps3-wireless-mouse.gamecontroller.amgp does not exist.
Xlib:  extension "GLX" missing on display ":15".
Xlib:  extension "GLX" missing on display ":15".
[8716:8716:1208/143658:ERROR:gl_surface_glx.cc(343)] glxQueryVersion failed
[8716:8716:1208/143658:ERROR:gl_surface_x11.cc(56)] GLSurfaceGLX::InitializeOneOff failed.
[8716:8716:1208/143658:ERROR:gpu_child_thread.cc(243)] Exiting GPU process due to errors during initialization
[8651:8651:1208/143658:ERROR:background_mode_manager_aura.cc(13)] Not implemented reached in virtual void BackgroundModeManager::EnableLaunchOnStartup(bool)
[8651:8680:1208/143658:ERROR:browser_gpu_channel_host_factory.cc(132)] Failed to launch GPU process.
[8651:8680:1208/143658:ERROR:browser_gpu_channel_host_factory.cc(132)] Failed to launch GPU process.
Fontconfig error: Cannot load default config file
```

**Comment by ProfessorKaos64** [comment] 2015-12-08 20:49
I will try this on a fresh snapshot base install when I get back soon. Ignore the first 3 lines, which is typical since you are running it in desktop mode. The issue is that missing antimicro profile.  Can you link a github paste of /tmp/dumps/ ... I believe it is steam_stdout.log or .txt. I'll let you know how I make out. I will chooes the exact ps3-wireless-mouse selection when settings up Netflix. To confirm, you are following the process on the [wiki page](https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Web-Apps), correct?

**Comment by ProfessorKaos64** [comment] 2015-12-08 23:23
Pushed some fixes out to the script code. Most of this boiled down to no write access but owned by steam user) of /home/steam/.config/google-chrome:
```
Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.
```

Put a permissions correction in there to fix it up. The permissions were being applied to the wrong directory. I apologize for that.

**Comment by dmbreton** [comment] 2015-12-09 20:44
It's working now.  Thanks for the help.

Just out of curiosity, are there keyboard shortcuts for the netflix web app?  I could not find details in my searches.

**Comment by ProfessorKaos64** [comment] 2015-12-09 20:49
That would be in the wiki:
https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Web-Apps

For keyboard shortcuts, it would be the same as what is standard keyboard shortucts
https://support.google.com/chrome/answer/157179?hl=en

I only augment gamepad controls. I'll add that link to the wiki page anyway.

@pogipants , can you confirm as well and close?

**Comment by dmbreton** [comment] 2015-12-09 21:02
Yup you can can close it.  It's all working well.  Thanks

**Closed** 2015-12-09 21:03 UTC
Labels: waiting for user
