### ISSUE TITLE
PlayOnLinux+BPM script not correctly exiting to BPM

### ISSUE THREAD

**Issue by BJSerpas** [ProfessorKaos64/SteamOS-Tools#119] opened 2016-01-12 09:40 UTC
I just wanted to quickly point out that there might be something wrong with the current script used to launch Steam for Windows games through Big Picture Mode (/cfgs/wine/pol-game-launcher.skel). I see that the bottom of the script is supposed to be listening to see if the game has been closed, and if it has, exit to BPM while properly closing the wineserver. Unfortunately, with every game I've tested, this never happens. Once the game mexe has been fully closed, Steam will stay running, and the wine virtual desktop will persist until I force exit to BPM through the overlay.

I hope that I'm not the only one with this issue, and that I can lend a hand if necessary.

**Comment by ProfessorKaos64** [comment] 2016-01-12 13:00
Can you note a few games? I will try to replicate this. Please attach a Gist or Pastebin of your launcher file. I will add stdout/stderr logging to the skeleton file that pushes to /tmp/pol-game.log.

**Comment by BJSerpas** [comment] 2016-01-12 23:55
Sure. A few games I have tested are Undertale, Mirror's Edge, and Sonic Adventure 2. For Sonic Adventure 2, I wanted to skip right to the game, so I renamed sonic2app.exe to Launcher.exe, but the script should still be monitoring that name, so it shouldn't be a problem. I'll get you some launcher files for those as soon as I can.

**Comment by ProfessorKaos64** [comment] 2016-01-13 00:28
Please read issue #155 (closed) carefully, this may apply to all your games, but is specifically about Sonic Adventure 2. After more feedback, the information in this issue may make it into the wiki.

**Comment by BJSerpas** [comment] 2016-01-13 00:39
Well, while originally I was having some issues with Mirror's Edge closing Steam but hanging on the wine virtual desktop, that was more of a one-off thing, and I'm once again having issues with Sonic Adventure 2. I did rename the game .exe to "Launcher.exe" to force Steam to load right into the game,but it looks like this is interfering with the script. I made 100% sure that GAME_EXE is set to "Launcher.exe," but since this is not the original name of the executable, maybe it's causing issues.

I can post any other information you need, but I'm using the same modified template to launch Sonic Adventure 2 as in issue 115, with GAME_EXE="Launcher.exe" being the only difference. I've loaded the game about 5 times now just to make extra sure I'm not wasting anyone's time here, but it is definitely not closing correctly.

**Comment by Ryochan7** [comment] 2016-01-13 02:38
Just tried this and Launcher.exe is seen as launcher.exe; that is the case when using the original exe and also when renaming sonic2app.exe. I don't know why it would be lowercase but that is what it shows up as. In that case, the script will never see the application and hang at the until loop.

It looks like a case-insensitive search is needed. SteamOS does not have a version of pgrep that can perform a case-insensitive search though. Something like this seems to work based on some light testing.

```
# Wait for application to be launched.
until [ -n "$(ps ax -o comm= | grep -i "$GAME_EXE")" ]; do
  sleep 2
done;

# Stay in loop while the game is running.
while [ -n "$(ps ax -o comm= | grep -i "$GAME_EXE")" ]; do
  sleep 2
done;
```

**Comment by ProfessorKaos64** [comment] 2016-01-13 03:10
I agree, thanks @Ryochan7. I'll test some of that code soon. This is probably going to be more of an issue for people (case insensitive Windows tomfoolery). Thank you.

**Comment by ProfessorKaos64** [comment] 2016-01-26 13:18
Confirmed this does work on games I have used recently. Closing.

**Closed by ProfessorKaos64** 2016-01-26 13:18 UTC
Labels: investigating
